version: '3'
services:
  plumelog:
    #此镜像是基于plumelog-3.5.3版本
    image: registry.cn-shanghai.aliyuncs.com/lensman_dev/plumelog:1.0
    container_name: plumelog
    ports:
      - "8891:8891"
    environment:
      plumelog.model: redis
      plumelog.queue.redis.redisHost: redis:6379
      plumelog.queue.redis.redisPassWord: 521521
      plumelog.queue.redis.redisDb: 0
      plumelog.es.esHosts: elasticsearch:9200
      login.username: admin
      login.password: 521521
    depends_on:
      - elasticsearch
      - redis
  redis:
    image: registry.cn-hangzhou.aliyuncs.com/kennylee/redis
    container_name: "redis"
    ports:
      - "6379:6379"
    volumes:
      - ./plumelog/redis/data/:/data/
      - ./plumelog/redis/log/:/var/log/redis/
    command:
      --requirepass "521521" #这一行是设置密码
  elasticsearch:
    image: elasticsearch:7.12.1
    container_name: elasticsearch
    environment:
      - "cluster.name=elasticsearch" #设置集群名称为elasticsearch
      - "discovery.type=single-node" #以单一节点模式启动
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m" #设置使用jvm内存大小
    volumes:
      - ./plumelog/elk/es/plugins:/usr/share/elasticsearch/plugins #插件文件挂载
      - ./plumelog/elk/es/data:/usr/share/elasticsearch/data #数据文件挂载
    ports:
      - 9200:9200
      - 9300:9300
